structure ThreeDigitsProblems =
struct
    (* type problem = {id : int, group : string, nums : int list}*)
    type problem = {id : int, group : string, nums : int list};

    val problems = [
        {id = 1,   group = "Beginner",                 nums = []},
        {id = 2,   group = "Beginner",                 nums = []},
        {id = 3,   group = "Beginner",                 nums = []},
        {id = 4,   group = "Halfway",                  nums = []},
        {id = 5,   group = "Halfway",                  nums = []},
        {id = 6,   group = "Halfway",                  nums = []},
        {id = 7,   group = "Halfway",                  nums = []},
        {id = 8,   group = "Halfway",                  nums = []},
        {id = 9,   group = "Halfway",                  nums = []},
        {id = 10,  group = "Seven Fifty",              nums = []},
        {id = 11,  group = "Seven Fifty",              nums = []},
        {id = 12,  group = "Seven Fifty",              nums = []},
        {id = 13,  group = "Seven Fifty",              nums = []},
        {id = 14,  group = "Seven Fifty",              nums = []},
        {id = 15,  group = "Seven Fifty",              nums = []},
        {id = 16,  group = "Full #1",                  nums = []},
        {id = 17,  group = "Full #1",                  nums = []},
        {id = 18,  group = "Full #1",                  nums = []},
        {id = 19,  group = "Full #1",                  nums = []},
        {id = 20,  group = "Full #1",                  nums = []},
        {id = 21,  group = "Full #1",                  nums = []},
        {id = 22,  group = "Full #1",                  nums = []},
        {id = 23,  group = "Full #1",                  nums = []},
        {id = 24,  group = "Full #1",                  nums = []},
        {id = 25,  group = "Full #1",                  nums = []},
        {id = 26,  group = "Full #1",                  nums = []},
        {id = 27,  group = "Full #1",                  nums = []},
        {id = 28,  group = "Full #1",                  nums = []},
        {id = 29,  group = "Full #1",                  nums = []},
        {id = 30,  group = "Full #1",                  nums = []},
        {id = 31,  group = "Full #1",                  nums = []},
        {id = 32,  group = "Full #1",                  nums = []},
        {id = 33,  group = "Full #1",                  nums = []},
        {id = 34,  group = "Full #1",                  nums = []},
        {id = 35,  group = "Full #1",                  nums = []},
        {id = 36,  group = "Full #1",                  nums = []},
        {id = 37,  group = "Full #1",                  nums = []},
        {id = 38,  group = "Full #1",                  nums = []},
        {id = 39,  group = "Full #1",                  nums = []},
        {id = 40,  group = "Full #1",                  nums = []},
        {id = 41,  group = "Full #1",                  nums = []},
        {id = 42,  group = "Full #1",                  nums = []},
        {id = 43,  group = "Full #1",                  nums = []},
        {id = 44,  group = "Full #1",                  nums = []},
        {id = 45,  group = "Full #1",                  nums = []},
        {id = 46,  group = "Full #1",                  nums = []},
        {id = 47,  group = "Full #1",                  nums = []},
        {id = 48,  group = "Full #1",                  nums = []},
        {id = 49,  group = "Full #1",                  nums = []},
        {id = 50,  group = "Full #1",                  nums = []},
        {id = 51,  group = "Full #1",                  nums = []},
        {id = 52,  group = "Full #1",                  nums = []},
        {id = 53,  group = "Full #1",                  nums = []},
        {id = 54,  group = "Full #1",                  nums = []},
        {id = 55,  group = "Full #1",                  nums = []},
        {id = 56,  group = "Full #1",                  nums = []},
        {id = 57,  group = "Full #1",                  nums = []},
        {id = 58,  group = "Full #1",                  nums = []},
        {id = 59,  group = "Full #1",                  nums = []},
        {id = 60,  group = "Full #1",                  nums = []},
        {id = 61,  group = "Awkward Range",            nums = []},
        {id = 62,  group = "Awkward Range",            nums = []},
        {id = 63,  group = "Awkward Range",            nums = []},
        {id = 64,  group = "Awkward Range",            nums = []},
        {id = 65,  group = "Awkward Range",            nums = []},
        {id = 66,  group = "Awkward Range",            nums = []},
        {id = 67,  group = "Awkward Range",            nums = []},
        {id = 68,  group = "Awkward Range",            nums = []},
        {id = 69,  group = "Awkward Range",            nums = []},
        {id = 70,  group = "Awkward Range",            nums = []},
        {id = 71,  group = "Awkward Range",            nums = []},
        {id = 72,  group = "Awkward Range",            nums = []},
        {id = 73,  group = "Awkward Range",            nums = []},
        {id = 74,  group = "Awkward Range",            nums = []},
        {id = 75,  group = "Awkward Range",            nums = []},
        {id = 76,  group = "Prime Time",               nums = []},
        {id = 77,  group = "Prime Time",               nums = []},
        {id = 78,  group = "Prime Time",               nums = []},
        {id = 79,  group = "Prime Time",               nums = []},
        {id = 80,  group = "Prime Time",               nums = []},
        {id = 81,  group = "Prime Time",               nums = []},
        {id = 82,  group = "Prime Time",               nums = []},
        {id = 83,  group = "Prime Time",               nums = []},
        {id = 84,  group = "Prime Time",               nums = []},
        {id = 85,  group = "Full #2",                  nums = []},
        {id = 86,  group = "Full #2",                  nums = []},
        {id = 87,  group = "Full #2",                  nums = []},
        {id = 88,  group = "Full #2",                  nums = []},
        {id = 89,  group = "Full #2",                  nums = []},
        {id = 90,  group = "Full #2",                  nums = []},
        {id = 91,  group = "Full #2",                  nums = []},
        {id = 92,  group = "Full #2",                  nums = []},
        {id = 93,  group = "Full #2",                  nums = []},
        {id = 94,  group = "Full #2",                  nums = []},
        {id = 95,  group = "Full #2",                  nums = []},
        {id = 96,  group = "Full #2",                  nums = []},
        {id = 97,  group = "Full #2",                  nums = []},
        {id = 98,  group = "Full #2",                  nums = []},
        {id = 99,  group = "Full #2",                  nums = []},
        {id = 100, group = "Full #2",                  nums = []},
        {id = 101, group = "Full #2",                  nums = []},
        {id = 102, group = "Full #2",                  nums = []},
        {id = 103, group = "Full #2",                  nums = []},
        {id = 104, group = "Full #2",                  nums = []},
        {id = 105, group = "Full #2",                  nums = []},
        {id = 106, group = "Full #2",                  nums = []},
        {id = 107, group = "Full #2",                  nums = []},
        {id = 108, group = "Full #2",                  nums = []},
        {id = 109, group = "Full #2",                  nums = []},
        {id = 110, group = "Full #2",                  nums = []},
        {id = 111, group = "Full #2",                  nums = []},
        {id = 112, group = "Full #2",                  nums = []},
        {id = 113, group = "Full #2",                  nums = []},
        {id = 114, group = "Full #2",                  nums = []},
        {id = 115, group = "Full #2",                  nums = []},
        {id = 116, group = "Full #2",                  nums = []},
        {id = 117, group = "Full #2",                  nums = []},
        {id = 118, group = "Full #2",                  nums = []},
        {id = 119, group = "Full #2",                  nums = []},
        {id = 120, group = "Full #2",                  nums = []},
        {id = 121, group = "Awkward Range Reversed",   nums = []},
        {id = 121, group = "Awkward Range Reversed",   nums = []},
        {id = 122, group = "Awkward Range Reversed",   nums = []},
        {id = 123, group = "Awkward Range Reversed",   nums = []},
        {id = 124, group = "Awkward Range Reversed",   nums = []},
        {id = 125, group = "Awkward Range Reversed",   nums = []},
        {id = 126, group = "Awkward Range Reversed",   nums = []},
        {id = 127, group = "Awkward Range Reversed",   nums = []},
        {id = 128, group = "Awkward Range Reversed",   nums = []},
        {id = 129, group = "Awkward Range Reversed",   nums = []},
        {id = 130, group = "Awkward Range Reversed",   nums = []},
        {id = 131, group = "Awkward Range Reversed",   nums = []},
        {id = 131, group = "Awkward Range Reversed",   nums = []},
        {id = 132, group = "Awkward Range Reversed",   nums = []},
        {id = 133, group = "Awkward Range Reversed",   nums = []},
        {id = 134, group = "Awkward Range Reversed",   nums = []},
        {id = 135, group = "Awkward Range Reversed",   nums = []},
        {id = 136, group = "Awkward Range Reversed",   nums = []},
        {id = 137, group = "Awkward Range Reversed",   nums = []},
        {id = 138, group = "Awkward Range Reversed",   nums = []},
        {id = 139, group = "Awkward Range Reversed",   nums = []},
        {id = 140, group = "Awkward Range Reversed",   nums = []},
        {id = 141, group = "Awkward Range Reversed",   nums = []},
        {id = 141, group = "Awkward Range Reversed",   nums = []},
        {id = 142, group = "Awkward Range Reversed",   nums = []},
        {id = 143, group = "Awkward Range Reversed",   nums = []},
        {id = 144, group = "Awkward Range Reversed",   nums = []},
        {id = 145, group = "Awkward Range Reversed",   nums = []},
        {id = 146, group = "Awkward Range Reversed",   nums = []},
        {id = 147, group = "Awkward Range Reversed",   nums = []},
        {id = 148, group = "Awkward Range Reversed",   nums = []},
        {id = 149, group = "Awkward Range Reversed",   nums = []},
        {id = 150, group = "Awkward Range Reversed",   nums = []},
        {id = 151, group = "We Aren't Divisible By 2", nums = []},
        {id = 152, group = "We Aren't Divisible By 2", nums = []},
        {id = 153, group = "We Aren't Divisible By 2", nums = []},
        {id = 154, group = "We Aren't Divisible By 2", nums = []},
        {id = 155, group = "We Aren't Divisible By 2", nums = []},
        {id = 156, group = "We Aren't Divisible By 2", nums = []},
        {id = 157, group = "We Aren't Divisible By 2", nums = []},
        {id = 158, group = "We Aren't Divisible By 2", nums = []},
        {id = 159, group = "We Aren't Divisible By 2", nums = []},
        {id = 160, group = "We Aren't Divisible By 2", nums = []},
        {id = 161, group = "We Aren't Divisible By 2", nums = []},
        {id = 162, group = "We Aren't Divisible By 2", nums = []},
        {id = 163, group = "We Aren't Divisible By 2", nums = []},
        {id = 164, group = "We Aren't Divisible By 2", nums = []},
        {id = 165, group = "We Aren't Divisible By 2", nums = []},
        {id = 166, group = "We Aren't Divisible By 2", nums = []},
        {id = 167, group = "We Aren't Divisible By 2", nums = []},
        {id = 168, group = "We Aren't Divisible By 2", nums = []},
        {id = 169, group = "We Aren't Divisible By 2", nums = []},
        {id = 170, group = "We Aren't Divisible By 2", nums = []},
        {id = 171, group = "We Aren't Divisible By 2", nums = []},
        {id = 172, group = "We Aren't Divisible By 2", nums = []},
        {id = 173, group = "We Aren't Divisible By 2", nums = []},
        {id = 174, group = "We Aren't Divisible By 2", nums = []},
        {id = 175, group = "We Aren't Divisible By 2", nums = []},
        {id = 176, group = "We Aren't Divisible By 2", nums = []},
        {id = 177, group = "We Aren't Divisible By 2", nums = []},
        {id = 178, group = "We Aren't Divisible By 2", nums = []},
        {id = 179, group = "We Aren't Divisible By 2", nums = []},
        {id = 180, group = "We Aren't Divisible By 2", nums = []},
        {id = 181, group = "Full #3",                  nums = []},
        {id = 182, group = "Full #3",                  nums = []},
        {id = 183, group = "Full #3",                  nums = []},
        {id = 184, group = "Full #3",                  nums = []},
        {id = 185, group = "Full #3",                  nums = []},
        {id = 186, group = "Full #3",                  nums = []},
        {id = 187, group = "Full #3",                  nums = []},
        {id = 188, group = "Full #3",                  nums = []},
        {id = 189, group = "Full #3",                  nums = []},
        {id = 190, group = "Full #3",                  nums = []},
        {id = 191, group = "Full #3",                  nums = []},
        {id = 192, group = "Full #3",                  nums = []},
        {id = 193, group = "Full #3",                  nums = []},
        {id = 194, group = "Full #3",                  nums = []},
        {id = 195, group = "Full #3",                  nums = []},
        {id = 196, group = "Full #3",                  nums = []},
        {id = 197, group = "Full #3",                  nums = []},
        {id = 198, group = "Full #3",                  nums = []},
        {id = 199, group = "Full #3",                  nums = []},
        {id = 200, group = "Full #3",                  nums = []},
        {id = 201, group = "Full #3",                  nums = []},
        {id = 202, group = "Full #3",                  nums = []},
        {id = 203, group = "Full #3",                  nums = []},
        {id = 204, group = "Full #3",                  nums = []},
        {id = 205, group = "Full #3",                  nums = []},
        {id = 206, group = "Full #3",                  nums = []},
        {id = 207, group = "Full #3",                  nums = []},
        {id = 208, group = "Full #3",                  nums = []},
        {id = 209, group = "Full #3",                  nums = []},
        {id = 210, group = "Full #3",                  nums = []},
        {id = 211, group = "Full #3",                  nums = []},
        {id = 212, group = "Full #3",                  nums = []},
        {id = 213, group = "Full #3",                  nums = []},
        {id = 214, group = "Full #3",                  nums = []},
        {id = 215, group = "Full #3",                  nums = []},
        {id = 216, group = "Full #3",                  nums = []},
        {id = 217, group = "Full #3",                  nums = []},
        {id = 218, group = "Full #3",                  nums = []},
        {id = 219, group = "Full #3",                  nums = []},
        {id = 220, group = "Full #3",                  nums = []},
        {id = 221, group = "Full #3",                  nums = []},
        {id = 222, group = "Full #3",                  nums = []},
        {id = 223, group = "Full #3",                  nums = []},
        {id = 224, group = "Full #3",                  nums = []},
        {id = 225, group = "Full #3",                  nums = []},
        {id = 226, group = "Full #3",                  nums = []},
        {id = 227, group = "Full #3",                  nums = []},
        {id = 228, group = "Full #3",                  nums = []},
        {id = 229, group = "Full #3",                  nums = []},
        {id = 230, group = "Full #3",                  nums = []},
        {id = 231, group = "Full #3",                  nums = []},
        {id = 232, group = "Full #3",                  nums = []},
        {id = 233, group = "Full #3",                  nums = []},
        {id = 234, group = "Full #3",                  nums = []},
        {id = 235, group = "Full #3",                  nums = []},
        {id = 236, group = "Full #3",                  nums = []},
        {id = 237, group = "Full #3",                  nums = []},
        {id = 238, group = "Full #3",                  nums = []},
        {id = 239, group = "Full #3",                  nums = []},
        {id = 240, group = "Full #3",                  nums = []},
        {id = 241, group = "Threes",                   nums = []},
        {id = 242, group = "Threes",                   nums = []},
        {id = 243, group = "Threes",                   nums = []},
        {id = 244, group = "Threes",                   nums = []},
        {id = 245, group = "Threes",                   nums = []},
        {id = 246, group = "Threes",                   nums = []},
        {id = 247, group = "Threes",                   nums = []},
        {id = 248, group = "Threes",                   nums = []},
        {id = 249, group = "Threes",                   nums = []},
        {id = 250, group = "Threes",                   nums = []},
        {id = 251, group = "Threes",                   nums = []},
        {id = 252, group = "Threes",                   nums = []},
        {id = 253, group = "Threes",                   nums = []},
        {id = 254, group = "Threes",                   nums = []},
        {id = 255, group = "Threes",                   nums = []},
        {id = 256, group = "Pure Three Digits",        nums = []},
        {id = 257, group = "Pure Three Digits",        nums = []},
        {id = 258, group = "Pure Three Digits",        nums = []},
        {id = 259, group = "Pure Three Digits",        nums = []},
        {id = 260, group = "Pure Three Digits",        nums = []},
        {id = 261, group = "Pure Three Digits",        nums = []},
        {id = 262, group = "Pure Three Digits",        nums = []},
        {id = 263, group = "Pure Three Digits",        nums = []},
        {id = 264, group = "Pure Three Digits",        nums = []},
        {id = 265, group = "Pure Three Digits",        nums = []},
        {id = 266, group = "Pure Three Digits",        nums = []},
        {id = 267, group = "Pure Three Digits",        nums = []},
        {id = 268, group = "Pure Three Digits",        nums = []},
        {id = 269, group = "Pure Three Digits",        nums = []},
        {id = 270, group = "Pure Three Digits",        nums = []},
        {id = 271, group = "Pure Three Digits",        nums = []},
        {id = 272, group = "Pure Three Digits",        nums = []},
        {id = 273, group = "Pure Three Digits",        nums = []},
        {id = 274, group = "Pure Three Digits",        nums = []},
        {id = 275, group = "Pure Three Digits",        nums = []},
        {id = 276, group = "Pure Three Digits",        nums = []},
        {id = 277, group = "Pure Three Digits",        nums = []},
        {id = 278, group = "Pure Three Digits",        nums = []},
        {id = 279, group = "Pure Three Digits",        nums = []},
        {id = 280, group = "Pure Three Digits",        nums = []},
        {id = 281, group = "Pure Three Digits",        nums = []},
        {id = 282, group = "Pure Three Digits",        nums = []},
        {id = 283, group = "Pure Three Digits",        nums = []},
        {id = 284, group = "Pure Three Digits",        nums = []},
        {id = 285, group = "Pure Three Digits",        nums = []},
        {id = 286, group = "Full #4",                  nums = []},
        {id = 287, group = "Full #4",                  nums = []},
        {id = 288, group = "Full #4",                  nums = []},
        {id = 289, group = "Full #4",                  nums = []},
        {id = 290, group = "Full #4",                  nums = []},
        {id = 291, group = "Full #4",                  nums = []},
        {id = 292, group = "Full #4",                  nums = []},
        {id = 293, group = "Full #4",                  nums = []},
        {id = 294, group = "Full #4",                  nums = []},
        {id = 295, group = "Full #4",                  nums = []},
        {id = 296, group = "Full #4",                  nums = []},
        {id = 297, group = "Full #4",                  nums = []},
        {id = 298, group = "Last Three",               nums = []},
        {id = 299, group = "Last Three",               nums = []},
        {id = 300, group = "Last Three",               nums = []}
    ];
end